### ISSUE TITLE
Tiling kb shortcuts apply to desktop (wallpaper) and Application Dashboard

### ISSUE THREAD

**Issue by sandro-mancuso** [darkstego/Mudeer#1]
Sometimes, if I'm not paying attention, I try to tile a window while none are active, or, since I'm using the meta key as the base for all my shortcuts, I accidentally trigger the Application Dashboard and subsequently move/resize it.

It's just an annoyance, I know how to reset the desktop if this happens even though I've disabled the fullscreen mudeer shortcut.  however, it "would be nice" if it were possible to limit the tiling to window type of Normal, Dialog, and Utility.  

When I get a chance this weekend I'll take a look and see if it's easy for me to do and submit a patch if I do, but I figure I'd note this here.

**Comment by darkstego** [comment]
This one was pretty easy to deal with and is handled in the latest commit.
