### ISSUE TITLE
Fullscreen tiled has stopped working

### ISSUE THREAD

**Issue by jp-bennett** [darkstego/Mudeer#16]
Sadly, the killer feature of Mudeer, tiling the fullscreen version of an application, has stopped working in Fedora 39 on KDE Wayland. It's running KDE Plasma 5.27.9, frameworks 5.111.0, and QT 5.15.11. 

Now, apps lose their fullscreen interface and go back to windowed when using a Mudeer shortcut to push them to a corner of the screen.

**Comment by darkstego** [comment]
Currently on Wayland, Plasma 5.27.9, frameworks 5.112.0, QT 5.15.11 and I can get the fullscreen effect.

I am testing with chrome running youtube on fullscreen. I can move into any section and it remains fullscreen.

What application are you using? And can you test if the behavior is still the same when you use the full-screen prefix button first before tiling.

**Comment by jp-bennett** [comment]
I swear it wasn't working for Chrome when I opened the ticket. And seems to be working now. I had tried out forcing Chrome into using its Wayland backend, which might be related. But since the effect has vanished, I'll close this for now.

**Comment by jp-bennett** [comment]
@darkstego I've figured out exactly how to replicate. It's setting the ozone platform to Wayland in chrome's expirimental flags. What threw me for a loop is that the restart that Chrome does after making this change isn't a full enough relaunch to change the backend. You have to kill all the chrome processes, then relaunch.

The fullscreen prefix does seem to do the trick, getting back to the desired behavior, thanks!
