### ISSUE TITLE
i am trader . i am not ablet to install this thing on window . please help 

### ISSUE THREAD

**Issue by stoper123** [darkstego/Mudeer#21]
C:\Users\parth>git clone https://github.com/darkstego/Mudeer.git
fatal: destination path 'Mudeer' already exists and is not an empty directory.

C:\Users\parth>cd Mudeer && make install
'make' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\parth\Mudeer>make install
'make' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\parth\Mudeer>install
'install' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\parth\Mudeer>

please make quick tutorial video  or explain step in detail . this step is suggested by chat gpt but seem like not working

**Comment by darkstego** [comment]
This project only works on KDE Plasma, and not on Windows. Look into something like Fancy Zones on Windows
