### ISSUE TITLE
Feature: FullScreen Top + Buttom

### ISSUE THREAD

**Issue by Mo8it** [darkstego/Mudeer#3]
Thanks for the awesome script!

Could you please add two shortcuts for "Fullscreen Top" and "Fullscreen Buttom". These would do the job of "Quick Tile Window to the Top/Buttom" but without the window jumping to the next monitor after second click. Adding the two options would make the experience more consistent.

**Comment by Mo8it** [comment]
I mean maximize like quick tile top.
![demo](https://user-images.githubusercontent.com/76752051/140585231-70380876-7338-40d1-8e32-ec49febfa604.gif)
When using quick tile, it either returns to original size or jumps to next monitor if you tile to right or left. Mudeer does not have this. It would be nice if Mudeer gets the same behavior, or alternatives to all quick tiles.

**Comment by TobiPeterG** [comment]
Hey there,

I'd also love this feature!
I have a 90° rotated display and would love to display fullscreen-content only on the lower half (or better third) of the screen, not the complete one.
Your script already includes a fullscreen left and right, so would this be possible to include?
Maybe even configurable, how big the bottom and top part of the screen are (relative to each other / complete screen size)?

Thank you very much!

**Comment by darkstego** [comment]
I have two ways to go about this, one would be making a list of shortcuts that deal with portrait mode screens (so splitting vertically instead of horizontally), the downside here is there becomes a ton of extra shortcuts that need to be mapped.

The second approach is changing the behavior based on the orientation of the monitor. So split by thirds would work left to right on horizontal displays and top to bottom on vertical ones. The advantage would be the number of shortcuts to remember are the same. The disadvantage is the choice of which type of splitting is dependent on the monitor orientation.

I think the second approach would be the best. It is simpler and minimizes the keys needed to map and memorize.

**Comment by TobiPeterG** [comment]
> I have two ways to go about this, one would be making a list of shortcuts that deal with portrait mode screens (so splitting vertically instead of horizontally), the downside here is there becomes a ton of extra shortcuts that need to be mapped.
> 
> The second approach is changing the behavior based on the orientation of the monitor. So split by thirds would work left to right on horizontal displays and top to bottom on vertical ones. The advantage would be the number of shortcuts to remember are the same. The disadvantage is the choice of which type of splitting is dependent on the monitor orientation.
> 
> I think the second approach would be the best. It is simpler and minimizes the keys needed to map and memorize. 

Uh the second approach sounds pretty smart.
The only disadvantage I could think of by the second approach would be that you have keyboard shortcuts aligned to fit left to right, not top to bottom.
Though this is a minor inconvenience. Having the same shortcuts probably makes up for it.

**Comment by darkstego** [comment]
>Would it also be possible to have a 3-way full-screen behavior (so not only left, right, but left, center, right / top, center, bottom)? :o

Could you elaborate? I am unsure how 3 way full screen behavior works. As in ignore panels?

> Oh and another question: is it possible to change the behavior of kwin in a way that when you make an application full-screen/maximized in a specific area of the screen to automatically tile to just that part (e.g. I double click on the title on the left half of the screen -> window becomes full-screen/maximized only on left half)

Not that I know of. The maximize behavior isn't customizable in kwin as far as I can tell.

**Comment by TobiPeterG** [comment]
> >Would it also be possible to have a 3-way full-screen behavior (so not only left, right, but left, center, right / top, center, bottom)? :o
> 
> Could you elaborate? I am unsure how 3 way full screen behavior works. As in ignore panels?
> 

Yeah, sure, I mean like playing a video or game, ignoring panels, the video on top of everything; just not two next to each other, but three, each taking up a third of the screen. 
I hope that's more clear. 😅

> > Oh and another question: is it possible to change the behavior of kwin in a way that when you make an application full-screen/maximized in a specific area of the screen to automatically tile to just that part (e.g. I double click on the title on the left half of the screen -> window becomes full-screen/maximized only on left half)
> 
> Not that I know of. The maximize behavior isn't customizable in kwin as far as I can tell. 

Ah OK, good to know, thanks! :)

**Comment by darkstego** [comment]
So the fullscreen behavior seems to be kinda limited at the moment with only laft and right. I do have an idea of a full screen toggle shortcut. When toggle is on all shortcuts ignore panels and gaps, and when off they behave like they do now. That way you get all the tiling options in fullscreen.

**Comment by nclarius** [comment]
> Oh and another question: is it possible to change the behavior of kwin in a way that when you make an application full-screen/maximized in a specific area of the screen to automatically tile to just that part (e.g. I double click on the title on the left half of the screen -> window becomes full-screen/maximized only on left half)

Do you mean the second feature showcased in https://store.kde.org/p/1309653/?

**Comment by TobiPeterG** [comment]
> So the fullscreen behavior seems to be kinda limited at the moment with only laft and right. I do have an idea of a full screen toggle shortcut. When toggle is on all shortcuts ignore panels and gaps, and when off they behave like they do now. That way you get all the tiling options in fullscreen.
> 
> But I won't change the default behavior so not to break things for users.

Yeah, that should work as well! :)

**Comment by darkstego** [comment]
Added support to more Fullscreen sizes and handled case of vertical displays in latest version (v3.0)

**Comment by TobiPeterG** [comment]
> Added support to more Fullscreen sizes and handled case of vertical displays in latest version (v3.0)

Thank you very much!
I installed v 3.0, but I can't find the shortcut to fullscreen applications at the top.
What is it called (what is the general naming scheme of the newly added vertical shortcuts)?
Thanks in advance!

**Comment by darkstego** [comment]
> 
> Thank you very much! I installed v 3.0, but I can't find the shortcut to fullscreen applications at the top. What is it called (what is the general naming scheme of the newly added vertical shortcuts)? Thanks in advance!

So the way fullscreen works has changed in the new version. I go over it in the Readme, but there is now a Fullscreen prefix shortcut that you press before any of the other shortcuts that will fullscreen the active window into the section of the screen. That way you can fullscreen into any section that you could tile to.

As for the vertical shortcuts. I just rearranged the existing shortcuts. So when the monitor is in portrait mode the shortcuts don't split left to right but rather top to bottom (by thirds or quarters or halves). And instead of top to bottom split for the CTRL and ALT keys they now split left and right in vertical monitors. You don't need to do anything on your end, just when you use the same shortcuts in a vertical screen the behavior changes.

**Comment by TobiPeterG** [comment]
> > Thank you very much! I installed v 3.0, but I can't find the shortcut to fullscreen applications at the top. What is it called (what is the general naming scheme of the newly added vertical shortcuts)? Thanks in advance!
> 
> So the way fullscreen works has changed in the new version. I go over it in the Readme, but there is now a Fullscreen prefix shortcut that you press before any of the other shortcuts that will fullscreen the active window into the section of the screen. That way you can fullscreen into any section that you could tile to.
> 
> As for the vertical shortcuts. I just rearranged the existing shortcuts. So when the monitor is in portrait mode the shortcuts don't split left to right but rather top to bottom (by thirds or quarters or halves). And instead of top to bottom split for the CTRL and ALT keys they now split left and right in vertical monitors. You don't need to do anything on your end, just when you use the same shortcuts in a vertical screen the behavior changes.

Thank you very much!
The shortcuts work now on a vertical display, though, the fullscreen prefix shortcut doesn't seem to work correctly.
When I hit win+ctrl+f, the next shortcut just works normally, without putting the window in fullscreen mode.
Am I missing something?

**Comment by darkstego** [comment]
> Thank you very much!
> The shortcuts work now on a vertical display, though, the fullscreen prefix shortcut doesn't seem to work correctly.
> When I hit win+ctrl+f, the next shortcut just works normally, without putting the window in fullscreen mode.
> Am I missing something?

Make sure you have the "Mudeer Ultrawide: Fullscreen Prefix" is mapped correctly in the system-settings shortcuts menu. Sometimes the shortcuts don't register when the script is loaded.

**Comment by TobiPeterG** [comment]
> > Thank you very much!
> > The shortcuts work now on a vertical display, though, the fullscreen prefix shortcut doesn't seem to work correctly.
> > When I hit win+ctrl+f, the next shortcut just works normally, without putting the window in fullscreen mode.
> > Am I missing something?
> 
> Make sure you have the "Mudeer Ultrawide: Fullscreen Prefix" is mapped correctly in the system-settings shortcuts menu. Sometimes the shortcuts don't register when the script is loaded.

YES, that was it! Thank you so much, it works perfectly now! :)

**Comment by TobiPeterG** [comment]
> > Thank you very much!
> > The shortcuts work now on a vertical display, though, the fullscreen prefix shortcut doesn't seem to work correctly.
> > When I hit win+ctrl+f, the next shortcut just works normally, without putting the window in fullscreen mode.
> > Am I missing something?
> 
> Make sure you have the "Mudeer Ultrawide: Fullscreen Prefix" is mapped correctly in the system-settings shortcuts menu. Sometimes the shortcuts don't register when the script is loaded.

Is there any way to buy you a coffee?

**Comment by darkstego** [comment]
> Is there any way to buy you a coffee?

I greatly appreciate the sentiment, but I don't really drink coffee. I am just glad people find this useful, and it has been a fun to work on it.
