### ISSUE TITLE
Gap does not space evenly

### ISSUE THREAD

**Issue by jonbestdev** [darkstego/Mudeer#4]
This might be because the space (gap amount) is being added around each window so then doubling the space between windows. A solution might be to add the gap amount to the desktops border too.

![image](https://user-images.githubusercontent.com/2657818/161395340-06d55642-c647-4a33-bddb-4e5aabeb3695.png)

**Comment by darkstego** [comment]
Yes that is true. The gap is around each window which means it appears double the width between windows compared to the edges. I think aesthetically you are correct that they should be the same all around. I will try to increase the gap around the edges to match.

**Comment by darkstego** [comment]
Fixed in commit 6a2b97874d01478c00c6611c40725fb594beebc3
